import streamlit as st
from Sendemail import enviar_email  # Importa a função Sendemail do arquivo Sendemail.py
import random
from streamlit_gsheets import GSheetsConnection
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from Verificação_datas import ler_datas_google_sheets
import toml

def manual_secao(df,config):
    st.write('<html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body><h2>Criar uma Seção: | Create a Section:</h2><p>Para criar uma nova seção, vá em "Criar uma seção nova". Insira seu e-mail na opção "Enter your email:" e clique em confirmar para receber o código da seção e a senha.</p><p>Compartilhe o código da seção com as pessoas que deseja para que elas possam escolher as datas disponíveis.</p><p><span style="color: darkblue;">To create a new section, go to "Create a new section". Enter your email in the "Enter your email:" option and click confirm to receive the section code and password.</p><p>Share the section code with the people you want so they can choose the available dates.</p></span></body></html>', unsafe_allow_html=True)
    st.write('<html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><h2>Já Possui uma Seção? | Already Have a Section?</h2><p>Se você já possui o código de uma seção, vá em "Enter a section - Entrar em uma seção existente" para escolher as datas em que está disponível.</p><p>Preencha o campo "Please inform the Section:" com o código da seção que você possui. Informe seu e-mail no campo "Please inform your email:", selecione o ano em "Year:" e o mês em "Month:".</p><p>Clique nas datas desejadas. Após selecionadas, clique em "Confirm". Pronto! Sua parte está feita. Agora é só aguardar o dono da seção gerar o relatório após todos escolherem as datas.</p><p><span style="color: darkblue;">If you already have a section code, go to "Enter a section - Enter an existing section" to choose the dates you are available.</p><p>Fill in the "Please inform the Section:" field with the section code you have. Enter your email in the "Please inform your email:" field, select the year in "Year:", and the month in "Month:".</p><p>Click on the desired dates. After selecting, click "Confirm". Your part is done. Now just wait for the section owner to generate the report after everyone has chosen the dates.</p></span></body></html>', unsafe_allow_html=True)
    st.write('<html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><h2>Todos já votaram? | Everyone Has Voted?</h2><p>Agora é a hora de descobrir quais datas foram mais votas. Vá em "Create a new session - Criar uma seção nova" insira os dados de seção no campo "Enter your Section:" e a senha no campo "Enter your Password:" que você recebeu por e-mail, clique em "View report - Gerar relatório" para gerar o relatório com as datas mais votadas!</p><p><span style="color: darkblue;">Now its time to find out which dates were most voted for. Go to "Create a new session - Create a new section", enter the section data in the "Enter your Section:" field and the password in the "Enter your Password:" field that you received by email, click "View report - Generate report" to generate the report with the most voted dates!</p></span></body></html>', unsafe_allow_html=True)
    